### ISSUE TITLE
bash commands with python to install xfluxgui doesn't work

### ISSUE THREAD

**Issue by aragon5956** [xflux-gui/xflux-gui#181] opened 2024-11-16 12:33 UTC
theses commands doesn't work : 

```
alexandre@alexandre-Matebook:~/Documents$ # Download fluxgui
cd /tmp
git clone "https://github.com/xflux-gui/fluxgui.git"
cd fluxgui
./download-xflux.py

# EITHER install system wide
sudo ./setup.py install --record installed.txt

# EXCLUSIVE OR, install in your home directory
#
# The fluxgui program installs
# into ~/.local/bin, so be sure to add that to your PATH if installing
# locally. In particular, autostarting fluxgui in Gnome will not work
# if the locally installed fluxgui is not on your PATH.
./setup.py install --user --record installed.txt
       
# Run flux
fluxgui
Clonage dans 'fluxgui'...
remote: Enumerating objects: 1749, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 1749 (delta 66), reused 117 (delta 60), pack-reused 1623 (from 1)
Réception d'objets: 100% (1749/1749), 1.60 Mio | 6.80 Mio/s, fait.
Résolution des deltas: 100% (864/864), fait.
Downloading 64-bit xflux ...
--2024-11-16 13:31:49--  https://justgetflux.com/linux/xflux64.tgz
Résolution de justgetflux.com (justgetflux.com)… 216.176.200.22
Connexion à justgetflux.com (justgetflux.com)|216.176.200.22|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 339845 (332K) [application/octet-stream]
Enregistre : ‘/tmp/xflux.tgz’

/tmp/xflux.tgz      100%[===================>] 331,88K   492KB/s    ds 0,7s    

2024-11-16 13:31:51 (492 KB/s) - ‘/tmp/xflux.tgz’ enregistré [339845/339845]

xflux
--2024-11-16 13:31:51--  https://justgetflux.com/linux/xflux11.tgz
Résolution de justgetflux.com (justgetflux.com)… 216.176.200.22
Connexion à justgetflux.com (justgetflux.com)|216.176.200.22|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 340420 (332K) [application/octet-stream]
Enregistre : ‘/tmp/xflux.tgz’

/tmp/xflux.tgz      100%[===================>] 332,44K   535KB/s    ds 0,6s    

2024-11-16 13:31:53 (535 KB/s) - ‘/tmp/xflux.tgz’ enregistré [340420/340420]

xflux11
--2024-11-16 13:31:53--  https://justgetflux.com/linux/xflux12.tgz
Résolution de justgetflux.com (justgetflux.com)… 216.176.200.22
Connexion à justgetflux.com (justgetflux.com)|216.176.200.22|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 340461 (332K) [application/octet-stream]
Enregistre : ‘/tmp/xflux.tgz’

/tmp/xflux.tgz      100%[===================>] 332,48K   402KB/s    ds 0,8s    

2024-11-16 13:31:55 (402 KB/s) - ‘/tmp/xflux.tgz’ enregistré [340461/340461]

xflux12
/usr/lib/python3/dist-packages/setuptools/dist.py:508: InformationOnly: Normalizing '2.0.1pre' to '2.0.1rc0'
  self.metadata.version = self._normalize_version(
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
warning: no files found matching 'COPYING'
warning: no files found matching 'MANIFEST'
warning: no files found matching 'README'
warning: no files found matching '*.desktop' under directory '*.svg'
warning: no files found matching '*.glade' under directory '*.py'
zip_safe flag not set; analyzing archive contents...
fluxgui.__pycache__.fluxapp.cpython-312: module references __file__
chmod: modification des droits de './dist': Opération non permise
chmod: modification des droits de './dist/f.lux_indicator_applet-2.0.1rc0-py3.12.egg': Opération non permise
chmod: modification des droits de './build': Opération non permise
chmod: modification des droits de './build/bdist.linux-x86_64': Opération non permise
chmod: modification des droits de './build/scripts-3.12': Opération non permise
chmod: modification des droits de './build/scripts-3.12/fluxgui': Opération non permise
chmod: modification des droits de './build/lib': Opération non permise
chmod: modification des droits de './build/lib/fluxgui': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/exceptions.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/preferences.glade': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/fluxapp.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/tabs': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/tabs/redshift.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/tabs/xflux.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/tabs/__init__.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/states.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/__init__.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/settings': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/settings/redshift.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/settings/xflux.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/settings/__init__.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/controller': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/controller/redshift.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/controller/xflux.py': Opération non permise
chmod: modification des droits de './build/lib/fluxgui/controller/__init__.py': Opération non permise
chmod: modification des droits de './installed.txt': Opération non permise
chmod: modification des droits de './f.lux_indicator_applet.egg-info': Opération non permise
chmod: modification des droits de './f.lux_indicator_applet.egg-info/dependency_links.txt': Opération non permise
chmod: modification des droits de './f.lux_indicator_applet.egg-info/top_level.txt': Opération non permise
chmod: modification des droits de './f.lux_indicator_applet.egg-info/PKG-INFO': Opération non permise
chmod: modification des droits de './f.lux_indicator_applet.egg-info/SOURCES.txt': Opération non permise
/usr/lib/python3/dist-packages/setuptools/dist.py:508: InformationOnly: Normalizing '2.0.1pre' to '2.0.1rc0'
  self.metadata.version = self._normalize_version(
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
error: Cannot update time stamp of directory 'f.lux_indicator_applet.egg-info'
/home/alexandre/.local/bin/fluxgui:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('f.lux-indicator-applet==2.0.1rc1', 'fluxgui')
Traceback (most recent call last):
  File "/home/alexandre/.local/bin/fluxgui", line 4, in <module>
    __import__('pkg_resources').run_script('f.lux-indicator-applet==2.0.1rc1', 'fluxgui')
  File "/home/alexandre/Documents/fluxgui/env/lib/python3.12/site-packages/pkg_resources/__init__.py", line 755, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/alexandre/Documents/fluxgui/env/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1720, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/fluxgui' not found in metadata at '/home/alexandre/Documents/fluxgui/env/lib/python3.12/site-packages/f.lux_indicator_applet-2.0.1rc1.dist-info'
alexandre@alexandre-Matebook:/tmp/fluxgui$ 
```
could you do something ?

**Comment by ntc2** [comment] 2024-11-17 05:46
I think this is a duplicate of https://github.com/xflux-gui/fluxgui/issues/178.

**Closed as not planned by ntc2** 2024-11-17 05:46 UTC
