### ISSUE TITLE
No ability to change daytime temperature

### ISSUE THREAD

**Issue by echrisinger** [xflux-gui/xflux-gui#52] opened 2017-02-21 11:07 UTC
This is critically important. I spend all day in front of PC and need to be able to fall asleep.

**Comment by ntc2** [comment] 2017-02-21 15:13
Duplicate of #14.

Note that RedShift supports changing the daytime temperature. This may be tricky to implement for Linux flux, since as far as I know there's no built in support for daytime color temps.

**Closed by ntc2** 2017-02-21 15:13 UTC
