### ISSUE TITLE
f.lux not working on ubuntu 14.04

### ISSUE THREAD

**Issue by EnforcerZhukov** [xflux-gui/xflux-gui#46] opened 2017-01-16 18:51 UTC
I'm trying to use f.lux with the GUI, but just doesn't work. Followed these steps: http://ubuntuhandbook.org/index.php/2016/03/install-f-lux-in-ubuntu-16-04/

Whenever I click on a preview color temperature, the GUI app freezes for a couple of seconds. Nothing else happens. What command should I run to attach here the debug?

**Comment by mDfRg** [comment] 2017-01-16 23:52
Downgrading to nvidia-340 worked for me. I believe it's a graphic card's driver issue.

**Comment by lizichen** [comment] 2017-01-17 00:16
Had a same situation on 16.04 LTS

**Comment by jpabbuehl** [comment] 2017-01-17 02:44
same with 16.10 LTS

**Comment by ntc2** [comment] 2017-01-17 05:43
You could try running `xflux` manually and see if you get an error:
``` shell
xflux -l 0 -g 0 -nofork
```
You'll want to stop any existing `xflux` processes before doing this.

It's likely you're running into an upstream issue (https://forum.justgetflux.com/topic/2373/sorry-we-only-support-8-and-10-bit-displays-right-now) that is often reported here (https://github.com/xflux-gui/xflux-gui/issues/27).

**Comment by EnforcerZhukov** [comment] 2017-01-21 10:59
Yes, it shows the displays error:
```
--------
Welcome to xflux (f.lux for X)
This will only work if you're running X on console.

Found 1 screen.
Sorry, we only support 8 and 10-bit displays right now.
david@Phenom-Ubuntu:~$ 
```

ATM i'm alternatively using redshift, although the GUI is not working, so I have to run it manually.

**Comment by mDfRg** [comment] 2017-01-23 03:34
@EnforcerZhukov @ntc2 same with me - "Sorry, we only support 8 and 10-bit displays right now.". Redshift 1.10 works, even the gui (redshift-gtk) version. Made a switch,

**Comment by ntc2** [comment] 2017-01-29 07:24
Duplicate of #27. We should probably change `fluxgui` to detect this problem and refer the user to Issue #27.

**Closed by ntc2** 2017-01-29 07:24 UTC
Labels: duplicate, needs info
