### ISSUE TITLE
Screen does not turn red on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicobonne** [xflux-gui/xflux-gui#39] opened 2016-11-28 16:49 UTC
I used flux on Ubuntu 16.04 for several months, then I re-installed Ubuntu 16.04. All the drivers are up-to-date, I can see the f.lux GUI and set colors and stuff, but the screen does not turn red. It doesn't turn red even with the previews on "preferences". I installed it with the ppa, as I did in the past.

**Comment by ntc2** [comment] 2016-11-28 21:29
I believe this is a duplicate of Issue #27.

**Closed by ntc2** 2016-11-28 21:29 UTC
