### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Thamaraiselvam** [xflux-gui/xflux-gui#28] opened 2016-08-30 09:37 UTC
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')

**Comment by holocronweaver** [comment] 2016-08-31 08:55
Please describe your system and the exact problem you are experiencing.

Is #27 by any chance related?

**Comment by kulicuu** [comment] 2016-09-01 18:40
Same here.  New kernel.  Ubuntu.  Same as #27

**Comment by ntc2** [comment] 2016-09-14 18:09
Sounds like this is a duplicate of #27.

**Closed by ntc2** 2016-09-14 18:09 UTC
Labels: duplicate, needs info
